apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment
  template:
    metadata:
      labels:
        app: appointment
    spec:
      containers:
      - name: appointment
        image: 794038216301.dkr.ecr.ap-south-1.amazonaws.com/gitops-webapp:appointment-${{ github.sha }}
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
spec:
  selector:
    app: appointment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
  type: ClusterIP
