apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient
  template:
    metadata:
      labels:
        app: patient
    spec:
      containers:
      - name: patient
        image: 794038216301.dkr.ecr.ap-south-1.amazonaws.com/gitops-webapp:patient-${{ github.sha }}
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
spec:
  selector:
    app: patient
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3002
  type: ClusterIP
